# Generated by Django 2.2 on 2019-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.CharField(max_length=100),
        ),
    ]
